codecov:
  token: 1811599e-cdf0-431f-bbca-002c54dc5dbb

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true
    patch: true
    changes: true

  ignore:
    - "Tests/**/*"