name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Tests
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_14.1.app/Contents/Developer']
    env:
      PROJECT: Steps.xcodeproj
      CONFIGURATION: Release
      DERIVED_PATH: .build/derivedData
    steps:
    - uses: actions/checkout@v2
    - name: Swift Build
      run: swift build
    - name: Bundle Install
      run: bundle install
    - name: Brew Upgrade
      run: |
        brew update
        brew outdated xctool || brew upgrade xctool
    - name: Test iOS
      run: |
        xcodebuild clean build test -project $PROJECT -scheme $SCHEME -configuration $CONFIGURATION -destination "$DESTINATION" -derivedDataPath $DERIVED_PATH | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF ios -J 'Steps' -D $DERIVED_PATH
      env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
          SCHEME: Steps-Package
          DESTINATION: platform=iOS Simulator,name=iPhone 11
    - name: Test macOS
      run: |
        xcodebuild clean build test -project $PROJECT -scheme $SCHEME -configuration $CONFIGURATION -destination "$DESTINATION" -derivedDataPath $DERIVED_PATH | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-macos.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF macos -J 'Steps' -D $DERIVED_PATH
      env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
          SCHEME: Steps-Package
          DESTINATION: platform=OS X
    - name: Test TVOS
      run: |
        xcodebuild clean build test -project $PROJECT -scheme $SCHEME -configuration $CONFIGURATION -destination "$DESTINATION" -derivedDataPath $DERIVED_PATH | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-tvos.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF tvos -J 'Steps' -D $DERIVED_PATH
      env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
          SCHEME: Steps-Package
          DESTINATION: platform=tvOS Simulator,name=Apple TV 4K (at 1080p)
