name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Tests
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_14.1.app/Contents/Developer']
    env:
      SCHEME: StepsTests
      CONFIGURATION: Debug
      DERIVED_PATH: .build/derivedData
      DEVELOPER_DIR: ${{ matrix.xcode }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Swift Build
      run: swift build
    - name: Bundle Install
      run: bundle install
    - name: Brew Upgrade
      run: |
        brew update
        brew outdated xctool || brew upgrade xctool
    - name: Test iOS
      run: |
        xcodebuild test -scheme $SCHEME -configuration $CONFIGURATION -destination "$DESTINATION" -derivedDataPath $DERIVED_PATH | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`
      env:
          DESTINATION: platform=iOS Simulator,name=iPhone 11
    - name: Test macOS
      run: |
        xcodebuild test -scheme $SCHEME -configuration $CONFIGURATION -destination "$DESTINATION" -derivedDataPath $DERIVED_PATH | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-macos.json" xcpretty -f `xcpretty-json-formatter`
      env:
          DESTINATION: platform=OS X
    - name: Test TVOS
      run: |
        xcodebuild test -scheme $SCHEME -configuration $CONFIGURATION -destination "$DESTINATION" -derivedDataPath $DERIVED_PATH | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-tvos.json" xcpretty -f `xcpretty-json-formatter`
      env:
          DESTINATION: platform=tvOS Simulator,name=Apple TV 4K (at 1080p)
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        name: Steps
        directory: $DESTINATION
        verbose: true
        fail_ci_if_error: true
